export type EditorLocale = "zh-CN" | "en";

export const copyByLocale = {
  "zh-CN": {
    pageTitle: "SolidLoom 建模工作台",
    untitledProject: "未命名项目",
    untitledModel: "未命名模型",
    noModel: "未选择模型",
    connecting: "连接中",
    serviceOnline: "本地服务已连接",
    serviceOffline: "本地服务离线",
    workspaceStatus: "工作台状态",
    currentPath: "当前位置",
    contextTools: "上下文工具",
    planned: "规划中",
    ready: "就绪",
    saving: "正在保存",
    saved: "更改已保存",
    unsaved: "有未保存更改",
    saveFailed: "保存失败",
    conflictReloaded: "模型已被其他操作修改，已载入最新修订",
    noSelection: "未选择对象",
    selectedModel: "已选择模型",
    units: "单位",
    undo: "撤销",
    redo: "重做",
    save: "保存",
    collapseLibrary: "折叠模型栏",
    expandLibrary: "展开模型栏",
    projectTree: "项目树",
    models: "模型",
    scenes: "场景",
    emptyScenes: "暂无场景",
    runScene: "进入运行",
    createModel: "新建模型",
    addModelReference: "引用到当前模型",
    removeModelReference: "移除模型引用",
    renameProject: "重命名项目",
    create: "创建",
    cancel: "取消",
    projectName: "项目名称",
    modelName: "模型名称",
    modelDescription: "模型说明",
    unit: "单位",
    revision: "修订",
    emptyModels: "暂无模型",
    collapseTree: "折叠全部",
    expandTree: "展开全部",
    resizeProjectTree: "调整项目树宽度",
    resizeInspectorWidth: "调整属性面板宽度",
    menu: "菜单",
    menuTitle: "工作台菜单",
    agentGuide: "智能体说明",
    apiDocs: "接口文档",
    language: "语言",
    theme: "主题",
    themeLight: "浅色",
    themeDark: "深色",
    themeSystem: "跟随系统",
    viewTools: "视图工具",
    rotate: "旋转",
    orthographic: "正交",
    viewportPreview: "参数化模型预览",
    viewportRendererFailed: "3D 视图暂时不可用，WebGL 上下文已丢失。",
    reloadViewport: "重新载入工作台",
    viewRight: "右面",
    viewLeft: "左面",
    viewTop: "顶部",
    viewBottom: "底部",
    viewFront: "前面",
    viewBack: "后面",
    viewCube: "视图方向控制器",
    selectModelHint: "从项目树中选择模型，或通过右键菜单新建模型。",
    features: "特征",
    properties: "属性",
    featureGraph: "特征图",
    groups: "分组",
    createGroup: "新建分组",
    newGroup: "分组",
    moveToGroup: "移入分组",
    removeFromGroup: "移出分组",
    dissolveGroup: "解散分组",
    groupTransform: "分组变换",
    referenceTransform: "引用实例变换",
    modelReferences: "模型引用",
    referencedModel: "源模型",
    liveRevision: "实时修订",
    referenceMissing: "引用的源模型不存在",
    referenceName: "实例名称",
    roomReferenceView: "房间显示方式",
    roomReferenceSource: "跟随源模型",
    roomReferenceInterior: "内部视图",
    roomReferenceExterior: "完整外壳",
    groupName: "分组名称",
    groupMembers: "成员",
    position: "位置",
    rotationLabel: "旋转",
    graphEmpty: "当前模型没有特征",
    add: "添加",
    cut: "切除",
    box: "长方体",
    cylinder: "圆柱体",
    parameters: "参数",
    width: "宽度",
    depth: "深度",
    height: "高度",
    cornerRadius: "圆角半径",
    cornerUniform: "统一圆角",
    cornerRadii: "八角圆角",
    cornerExpression: "圆角表达式",
    cornerExpressionHint: "支持 1、2、4 或 8 个值；“/”分隔底面与顶面。",
    cornerExpressionInvalid: "请输入 1、2、4 或 8 个非负数。",
    cornerLocalAxes: "方向使用对象局部坐标，旋转时随对象一起旋转。",
    cornerBottom: "底面 y−",
    cornerTop: "顶面 y+",
    apply: "应用",
    cornerAlgorithm: "圆角算法",
    cornerCircular: "标准圆弧",
    cornerSmooth: "高阶平滑",
    radius: "半径",
    appearance: "外观",
    material: "材质",
    materialDefault: "默认",
    materialWood: "木质",
    materialMetal: "金属",
    materialPlastic: "塑料",
    materialGlass: "玻璃",
    materialFabric: "织物",
    materialRubber: "橡胶",
    color: "颜色",
    resetAppearance: "重置外观",
    useMaterialColor: "使用材质颜色",
    voxelSkinTitle: "像素皮肤",
    voxelSkinModel: "手臂模型",
    voxelSkinClassic: "Classic · 4 像素",
    voxelSkinSlim: "Slim · 3 像素",
    voxelSkinSource: "皮肤来源",
    voxelSkinBuiltIn: "内置原创皮肤",
    voxelSkinImported: "本地导入皮肤",
    voxelSkinImport: "导入 64×64 PNG",
    voxelSkinReset: "恢复默认",
    voxelSkinHint: "兼容通用 64×64 皮肤布局，基础身体与略微外扩的透明服饰层会分别渲染；图片只保存在当前本地模型中。",
    voxelSkinInvalid: "请选择有效的 64×64 PNG 皮肤文件。",
    voxelSkinTooLarge: "皮肤文件不能超过 256 KB。",
    metadata: "模型信息",
    selectionSummary: "对象摘要",
    multipleSelection: "多选",
    selectedObjects: "已选择对象",
    size: "尺寸",
    volume: "体积",
    triangles: "三角形",
    mesh: "三角网格",
    proceduralShell: "程序化外壳",
    roomShell: "程序化房间",
    modelVariables: "模型变量",
    modelVariablesHint: "变量使用 CSS 自定义属性命名；数值可参与节点计算，颜色等外观变量由模型生成器统一应用。",
    nodeExpressions: "节点计算表达式",
    expressionTarget: "目标字段",
    expressionError: "部分表达式无法计算",
    proceduralMeshHint: "修改参数后会自动重建三角网格，并可撤销和保存。",
    wallThickness: "墙体厚度",
    floorThickness: "地板与天花板厚度",
    autoHideRoomSurfaces: "按视角自动隐藏近侧表面",
    doorSettings: "门设置",
    doorWidth: "门宽",
    doorHeight: "门高",
    doorPosition: "门位置 Z",
    windowSettings: "落地窗设置",
    fullWallWindow: "整墙玻璃幕墙",
    fullWallWindowHint: "开启后，玻璃会自动填满整面墙并跟随房间尺寸变化。",
    windowWidth: "落地窗宽度",
    windowHeight: "落地窗高度",
    windowSillHeight: "离地高度",
    windowPosition: "落地窗位置 X",
    outlineRadius: "轮廓圆角",
    edgeFilletRadius: "边缘倒圆",
    recessSettings: "凹槽设置",
    recessSpanX: "凹槽宽度 X",
    recessSpanY: "凹槽高度 Y",
    recessSpanZ: "凹槽深度 Z",
    recessCutDepth: "切入深度",
    recessRadius: "凹槽圆角",
    moveTool: "移动",
    rotateTool: "旋转",
    scaleTool: "缩放",
    planeCutTool: "平面切割",
    booleanTool: "布尔运算",
    union: "并集",
    intersection: "交集",
    difference: "差集",
    execute: "执行",
    reset: "重置",
    keepPositive: "保留正方向",
    preserveSources: "保留原对象",
    offset: "偏移",
    selectedCount: "已选对象",
    meshResultNotice: "结果为可保存的三角网格；生产级 B-Rep 求值仍为规划中。",
    multiTransformHint: "拖动 3D 操纵器统一变换当前多选对象。",
    operationFailed: "几何运算失败",
    booleanResult: "布尔结果",
    cutResult: "切割结果",
    annotationAssist: "注释辅助",
    annotationAssistActive: "注释辅助已开启 · 点击对象框后再添加 Codex 页面注释",
    annotationFeature: "对象",
    annotationGroup: "分组",
    annotationPath: "对象路径",
    annotationMembers: "成员",
    navigationMode: "漫游模式",
    navigationModeActive: "漫游模式 · 第一/第三人称单击视口锁定鼠标，移动鼠标控制镜头，Esc 退出",
    navigationGodCamera: "上帝视角",
    navigationFirstPerson: "第一人称",
    navigationThirdPerson: "第三人称",
    interactionPowerOn: "开启显示器",
    interactionPowerOff: "关闭显示器",
    interactionArticulationOpen: "打开笔记本",
    interactionArticulationClose: "合上笔记本",
    interactionContainerOpen: "查看容器",
    interactionContainerClose: "关闭容器",
    interactionContainerContents: "容器内容",
    interactionContainerCapacity: "容量",
    interactionContainerStore: "放入一个物品",
    interactionContainerTake: "取出最后一项",
    interactionContainerEmpty: "容器为空",
    interactionContainerSessionOnly: "试验状态仅保留在当前本地编辑会话中。",
    interactionSit: "坐下",
    interactionStand: "起身",
    interactionDoorOpen: "打开门",
    interactionDoorClose: "关闭门",
    interactionKeyHint: "E",
    joint: "关节",
    modelActions: "模型动作",
    posePresets: "姿态预设",
    animationClips: "循环动画",
    locomotionSpeed: "移动速度",
    locomotionIdle: "站立",
    locomotionWalk: "走路",
    locomotionTransition: "走跑过渡",
    locomotionRun: "奔跑",
    locomotionCycle: "步态周期",
    locomotionBlend: "奔跑混合",
    locomotionWalkReference: "走路基准",
    locomotionRunReference: "奔跑基准",
    locomotionTransitionStart: "过渡开始",
    locomotionTransitionEnd: "过渡完成",
    jointAngle: "开合角度",
    jointRange: "活动范围",
    jointTypeRevolute: "旋转关节",
    jointClose: "合上",
    jointOpen: "打开",
    jointClosed: "关闭",
    jointHalf: "半合",
    jointExpanded: "展开",
    keyboardShortcuts: "快捷键",
    shortcutViewportHint: "点击 3D 视口后启用镜头快捷键；输入框获得焦点时不会触发。",
    close: "关闭",
  },
  en: {
    pageTitle: "SolidLoom Modeling Workspace",
    untitledProject: "Untitled project",
    untitledModel: "Untitled model",
    noModel: "No model selected",
    connecting: "Connecting",
    serviceOnline: "Local service connected",
    serviceOffline: "Local service offline",
    workspaceStatus: "Workspace status",
    currentPath: "Current location",
    contextTools: "Context tools",
    planned: "Planned",
    ready: "Ready",
    saving: "Saving",
    saved: "Changes saved",
    unsaved: "Unsaved changes",
    saveFailed: "Save failed",
    conflictReloaded: "The model changed elsewhere; the latest revision was loaded",
    noSelection: "No object selected",
    selectedModel: "Selected model",
    units: "Units",
    undo: "Undo",
    redo: "Redo",
    save: "Save",
    collapseLibrary: "Collapse model library",
    expandLibrary: "Expand model library",
    projectTree: "Project tree",
    models: "Models",
    scenes: "Scenes",
    emptyScenes: "No scenes",
    runScene: "Run scene",
    createModel: "Create model",
    addModelReference: "Reference in current model",
    removeModelReference: "Remove model reference",
    renameProject: "Rename project",
    create: "Create",
    cancel: "Cancel",
    projectName: "Project name",
    modelName: "Model name",
    modelDescription: "Model description",
    unit: "Unit",
    revision: "Revision",
    emptyModels: "No models",
    collapseTree: "Collapse all",
    expandTree: "Expand all",
    resizeProjectTree: "Resize project tree width",
    resizeInspectorWidth: "Resize inspector width",
    menu: "Menu",
    menuTitle: "Workspace menu",
    agentGuide: "Agent guide",
    apiDocs: "API documentation",
    language: "Language",
    theme: "Theme",
    themeLight: "Light",
    themeDark: "Dark",
    themeSystem: "System",
    viewTools: "View tools",
    rotate: "Rotate",
    orthographic: "Orthographic",
    viewportPreview: "Parametric model preview",
    viewportRendererFailed: "The 3D view is temporarily unavailable because the WebGL context was lost.",
    reloadViewport: "Reload workspace",
    viewRight: "Right",
    viewLeft: "Left",
    viewTop: "Top",
    viewBottom: "Bottom",
    viewFront: "Front",
    viewBack: "Back",
    viewCube: "View orientation control",
    selectModelHint: "Select a model in the project tree, or create one from the context menu.",
    features: "Features",
    properties: "Properties",
    featureGraph: "Feature graph",
    groups: "Groups",
    createGroup: "Create group",
    newGroup: "Group",
    moveToGroup: "Move to group",
    removeFromGroup: "Remove from group",
    dissolveGroup: "Dissolve group",
    groupTransform: "Group transform",
    referenceTransform: "Reference transform",
    modelReferences: "Model references",
    referencedModel: "Source model",
    liveRevision: "Live revision",
    referenceMissing: "Referenced source model is missing",
    referenceName: "Instance name",
    roomReferenceView: "Room display",
    roomReferenceSource: "Follow source model",
    roomReferenceInterior: "Interior view",
    roomReferenceExterior: "Complete shell",
    groupName: "Group name",
    groupMembers: "Members",
    position: "Position",
    rotationLabel: "Rotation",
    graphEmpty: "This model has no features",
    add: "Add",
    cut: "Cut",
    box: "Box",
    cylinder: "Cylinder",
    parameters: "Parameters",
    width: "Width",
    depth: "Depth",
    height: "Height",
    cornerRadius: "Corner radius",
    cornerUniform: "Uniform radius",
    cornerRadii: "Eight-corner radii",
    cornerExpression: "Corner radius expression",
    cornerExpressionHint: "Use 1, 2, 4, or 8 values; “/” separates the bottom and top layers.",
    cornerExpressionInvalid: "Enter 1, 2, 4, or 8 non-negative numbers.",
    cornerLocalAxes: "Directions use local object axes and rotate with the object.",
    cornerBottom: "Bottom y−",
    cornerTop: "Top y+",
    apply: "Apply",
    cornerAlgorithm: "Corner algorithm",
    cornerCircular: "Circular arc",
    cornerSmooth: "High-order smooth",
    radius: "Radius",
    appearance: "Appearance",
    material: "Material",
    materialDefault: "Default",
    materialWood: "Wood",
    materialMetal: "Metal",
    materialPlastic: "Plastic",
    materialGlass: "Glass",
    materialFabric: "Fabric",
    materialRubber: "Rubber",
    color: "Color",
    resetAppearance: "Reset appearance",
    useMaterialColor: "Use material color",
    voxelSkinTitle: "Pixel skin",
    voxelSkinModel: "Arm model",
    voxelSkinClassic: "Classic · 4 px",
    voxelSkinSlim: "Slim · 3 px",
    voxelSkinSource: "Skin source",
    voxelSkinBuiltIn: "Built-in original skin",
    voxelSkinImported: "Locally imported skin",
    voxelSkinImport: "Import 64×64 PNG",
    voxelSkinReset: "Restore default",
    voxelSkinHint: "Uses the common 64×64 skin layout with base and overlay layers. The image stays in the local model.",
    voxelSkinInvalid: "Choose a valid 64×64 PNG skin file.",
    voxelSkinTooLarge: "The skin file must not exceed 256 KB.",
    metadata: "Model information",
    selectionSummary: "Object summary",
    multipleSelection: "Multiple selection",
    selectedObjects: "Selected objects",
    size: "Size",
    volume: "Volume",
    triangles: "Triangles",
    mesh: "Triangle mesh",
    proceduralShell: "Procedural shell",
    roomShell: "Procedural room",
    modelVariables: "Model variables",
    modelVariablesHint: "Variables use CSS custom-property names; numeric values drive expressions and appearance values are applied by the model generator.",
    nodeExpressions: "Node expressions",
    expressionTarget: "Target field",
    expressionError: "Some expressions could not be evaluated",
    proceduralMeshHint: "Changing a parameter rebuilds the triangle mesh and remains undoable and saveable.",
    wallThickness: "Wall thickness",
    floorThickness: "Floor and ceiling thickness",
    autoHideRoomSurfaces: "Auto-hide near surfaces by view",
    doorSettings: "Door settings",
    doorWidth: "Door width",
    doorHeight: "Door height",
    doorPosition: "Door position Z",
    windowSettings: "Floor-to-ceiling window settings",
    fullWallWindow: "Full-wall glass curtain",
    fullWallWindowHint: "The glass automatically fills the wall and follows room size changes.",
    windowWidth: "Window width",
    windowHeight: "Window height",
    windowSillHeight: "Floor clearance",
    windowPosition: "Window position X",
    outlineRadius: "Outline radius",
    edgeFilletRadius: "Edge fillet",
    recessSettings: "Recess settings",
    recessSpanX: "Recess width X",
    recessSpanY: "Recess height Y",
    recessSpanZ: "Recess depth Z",
    recessCutDepth: "Cut depth",
    recessRadius: "Recess radius",
    moveTool: "Move",
    rotateTool: "Rotate",
    scaleTool: "Scale",
    planeCutTool: "Plane cut",
    booleanTool: "Boolean",
    union: "Union",
    intersection: "Intersection",
    difference: "Difference",
    execute: "Execute",
    reset: "Reset",
    keepPositive: "Keep positive side",
    preserveSources: "Keep source objects",
    offset: "Offset",
    selectedCount: "Selected objects",
    meshResultNotice: "The result is a persistable triangle mesh; production B-Rep evaluation remains planned.",
    multiTransformHint: "Drag the 3D gizmo to transform the current multi-selection together.",
    operationFailed: "Geometry operation failed",
    booleanResult: "Boolean result",
    cutResult: "Cut result",
    annotationAssist: "Annotation assist",
    annotationAssistActive: "Annotation assist is active · Select an object target, then add a Codex page comment",
    annotationFeature: "Object",
    annotationGroup: "Group",
    annotationPath: "Object path",
    annotationMembers: "Members",
    navigationMode: "Walk mode",
    navigationModeActive: "Walk mode · In first/third person, click the viewport to lock the pointer; move to look; press Esc to exit",
    navigationGodCamera: "God view",
    navigationFirstPerson: "First person",
    navigationThirdPerson: "Third person",
    interactionPowerOn: "Turn on display",
    interactionPowerOff: "Turn off display",
    interactionArticulationOpen: "Open laptop",
    interactionArticulationClose: "Close laptop",
    interactionContainerOpen: "Inspect container",
    interactionContainerClose: "Close container",
    interactionContainerContents: "Container contents",
    interactionContainerCapacity: "Capacity",
    interactionContainerStore: "Store an item",
    interactionContainerTake: "Take last item",
    interactionContainerEmpty: "Container is empty",
    interactionContainerSessionOnly: "Playground state is kept only in this local editing session.",
    interactionSit: "Sit down",
    interactionStand: "Stand up",
    interactionDoorOpen: "Open door",
    interactionDoorClose: "Close door",
    interactionKeyHint: "E",
    joint: "Joint",
    modelActions: "Model actions",
    posePresets: "Pose presets",
    animationClips: "Looping animations",
    locomotionSpeed: "Movement speed",
    locomotionIdle: "Standing",
    locomotionWalk: "Walking",
    locomotionTransition: "Walk-run blend",
    locomotionRun: "Running",
    locomotionCycle: "Gait cycle",
    locomotionBlend: "Run blend",
    locomotionWalkReference: "Walk reference",
    locomotionRunReference: "Run reference",
    locomotionTransitionStart: "Blend start",
    locomotionTransitionEnd: "Blend end",
    jointAngle: "Opening angle",
    jointRange: "Motion range",
    jointTypeRevolute: "Revolute joint",
    jointClose: "Close",
    jointOpen: "Open",
    jointClosed: "Closed",
    jointHalf: "Half open",
    jointExpanded: "Expanded",
    keyboardShortcuts: "Keyboard shortcuts",
    shortcutViewportHint: "Click the 3D viewport to enable camera shortcuts. They stay inactive while editing a field.",
    close: "Close",
  },
} as const;
