import type { ModelAssetDefinition, ModelAssetManifest } from "@solidloom/shared";
import {
  coffeeMachineFeatureIds,
  coffeeMachineGroupIds,
  coffeeMachineJointIds,
  createCoffeeMachine,
  defaultCoffeeMachineParameters,
} from "./model.js";

const allFeatureIds = Object.values(coffeeMachineFeatureIds);
const silhouetteFeatureIds = [
  coffeeMachineFeatureIds.body,
  coffeeMachineFeatureIds.frontPanel,
  coffeeMachineFeatureIds.brewHead,
  coffeeMachineFeatureIds.tray,
  coffeeMachineFeatureIds.waterTank,
  coffeeMachineFeatureIds.leftFoot,
  coffeeMachineFeatureIds.rightFoot,
];
const simplifiedFeatureIds = [
  ...silhouetteFeatureIds,
  coffeeMachineFeatureIds.topCap,
  coffeeMachineFeatureIds.display,
  coffeeMachineFeatureIds.statusLight,
  coffeeMachineFeatureIds.powerSwitch,
  coffeeMachineFeatureIds.brewCollar,
  coffeeMachineFeatureIds.spout,
  coffeeMachineFeatureIds.cupRing,
  coffeeMachineFeatureIds.waterWindow,
  coffeeMachineFeatureIds.waterTankLid,
];

export const coffeeMachineManifest: ModelAssetManifest = {
  schemaVersion: 1,
  id: "cyber-factory-coffee-machine",
  displayName: "参数化咖啡机",
  description: "适用于办公室茶水区的紧凑咖啡机，包含电源、接近菜单触发、制作、取杯和补水语义锚点。",
  version: "1.2.0",
  kind: "asset",
  modelUnit: "mm",
  parameters: [
    {
      id: "width",
      label: "机身宽度",
      type: "number",
      defaultValue: defaultCoffeeMachineParameters.width,
      unit: "mm",
      minimum: 320,
      maximum: 520,
      step: 10,
    },
    {
      id: "height",
      label: "机身高度",
      type: "number",
      defaultValue: defaultCoffeeMachineParameters.height,
      unit: "mm",
      minimum: 460,
      maximum: 680,
      step: 10,
    },
    {
      id: "depth",
      label: "机身深度",
      type: "number",
      defaultValue: defaultCoffeeMachineParameters.depth,
      unit: "mm",
      minimum: 360,
      maximum: 560,
      step: 10,
    },
    {
      id: "finish",
      label: "机身配色",
      type: "select",
      defaultValue: defaultCoffeeMachineParameters.finish,
      options: ["graphite", "porcelain", "cobalt"],
    },
    {
      id: "powered",
      label: "电源状态",
      type: "boolean",
      defaultValue: defaultCoffeeMachineParameters.powered,
    },
  ],
  materials: [
    {
      id: "body-shell",
      label: "机身外壳",
      material: "plastic",
      color: "#303941",
      featureIds: [coffeeMachineFeatureIds.body, coffeeMachineFeatureIds.waterTankLid],
    },
    {
      id: "control-shell",
      label: "控制区与萃取头",
      material: "plastic",
      color: "#171D22",
      featureIds: [
        coffeeMachineFeatureIds.topCap,
        coffeeMachineFeatureIds.frontPanel,
        coffeeMachineFeatureIds.brewHead,
      ],
    },
    {
      id: "steel-hardware",
      label: "金属组件",
      material: "metal",
      color: "#AAB4B9",
      featureIds: [
        coffeeMachineFeatureIds.brewCollar,
        coffeeMachineFeatureIds.spout,
        coffeeMachineFeatureIds.tray,
        coffeeMachineFeatureIds.cupRing,
        coffeeMachineFeatureIds.steamButton,
      ],
    },
    {
      id: "glass-reservoir",
      label: "玻璃与水箱",
      material: "glass",
      color: "#79BFD2",
      featureIds: [
        coffeeMachineFeatureIds.display,
        coffeeMachineFeatureIds.waterTank,
        coffeeMachineFeatureIds.waterWindow,
      ],
    },
    {
      id: "control-accent",
      label: "控制强调色",
      material: "plastic",
      color: "#58D7C5",
      featureIds: [
        coffeeMachineFeatureIds.brewButton,
      ],
    },
    {
      id: "power-control",
      label: "电源开关与指示灯",
      material: "plastic",
      color: "#314047",
      featureIds: [
        coffeeMachineFeatureIds.powerSwitch,
        coffeeMachineFeatureIds.statusLight,
      ],
    },
    {
      id: "non-slip",
      label: "防滑与格栅",
      material: "rubber",
      color: "#151A1D",
      featureIds: [
        coffeeMachineFeatureIds.leftFoot,
        coffeeMachineFeatureIds.rightFoot,
        coffeeMachineFeatureIds.centerGrate,
        coffeeMachineFeatureIds.leftGrate,
        coffeeMachineFeatureIds.rightGrate,
      ],
    },
  ],
  placement: {
    upAxis: "y",
    groundY: 0,
    origin: [0, 0, 0],
    defaultScale: [1, 1, 1],
  },
  colliders: [
    {
      id: "machine-body-collider",
      label: "机身碰撞体",
      shape: "box",
      position: [0, defaultCoffeeMachineParameters.height / 2, 0],
      rotation: [0, 0, 0],
      size: [
        defaultCoffeeMachineParameters.width,
        defaultCoffeeMachineParameters.height,
        defaultCoffeeMachineParameters.depth,
      ],
      groupId: coffeeMachineGroupIds.body,
    },
    {
      id: "drip-tray-collider",
      label: "滴水托盘碰撞体",
      shape: "box",
      position: [0, 64, defaultCoffeeMachineParameters.depth * 0.62],
      rotation: [0, 0, 0],
      size: [
        defaultCoffeeMachineParameters.width * 0.78,
        32,
        defaultCoffeeMachineParameters.depth * 0.38,
      ],
      groupId: coffeeMachineGroupIds.tray,
    },
  ],
  anchors: [
    {
      id: "front-approach",
      label: "正面接近与菜单触发位",
      kind: "approach",
      position: [0, 0, defaultCoffeeMachineParameters.depth / 2 + 720],
      rotation: [0, 180, 0],
      range: 900,
      groupId: coffeeMachineGroupIds.body,
      tags: ["navigation", "front", "proximity", "menu-trigger"],
    },
    {
      id: "power-toggle",
      label: "切换电源",
      kind: "interaction",
      position: [-180, 330, defaultCoffeeMachineParameters.depth / 2 + 250],
      rotation: [0, 180, 0],
      range: 720,
      groupId: coffeeMachineGroupIds.control,
      tags: ["power", "toggle"],
    },
    {
      id: "brew-coffee",
      label: "制作咖啡",
      kind: "interaction",
      position: [0, 190, defaultCoffeeMachineParameters.depth / 2 + 270],
      rotation: [0, 180, 0],
      range: 720,
      groupId: coffeeMachineGroupIds.control,
      tags: ["beverage", "brew"],
    },
    {
      id: "cup-socket",
      label: "杯位",
      kind: "socket",
      position: [0, 84, defaultCoffeeMachineParameters.depth / 2 + 58],
      rotation: [0, 0, 0],
      range: 260,
      groupId: coffeeMachineGroupIds.tray,
      tags: ["cup", "placement"],
    },
    {
      id: "take-cup",
      label: "取杯",
      kind: "interaction",
      position: [0, 126, defaultCoffeeMachineParameters.depth / 2 + 250],
      rotation: [0, 180, 0],
      range: 680,
      groupId: coffeeMachineGroupIds.tray,
      tags: ["beverage", "pickup"],
    },
    {
      id: "refill-water",
      label: "补充水箱",
      kind: "interaction",
      position: [0, defaultCoffeeMachineParameters.height + 180, -defaultCoffeeMachineParameters.depth / 2 - 220],
      rotation: [-40, 0, 0],
      range: 720,
      jointId: coffeeMachineJointIds.waterTankLid,
      tags: ["maintenance", "water"],
    },
  ],
  joints: [{
    id: "water-tank-lid",
    label: "水箱翻盖",
    jointId: coffeeMachineJointIds.waterTankLid,
    semantic: "refill-access",
  }],
  lod: [
    {
      device: "desktop",
      levels: [
        { id: "desktop-full", maximumDistance: 3000, featureIds: allFeatureIds, triangleBudget: 1400 },
        { id: "desktop-medium", maximumDistance: 7000, featureIds: simplifiedFeatureIds, triangleBudget: 620 },
        { id: "desktop-silhouette", maximumDistance: 16000, featureIds: silhouetteFeatureIds, triangleBudget: 180 },
      ],
    },
    {
      device: "mobile",
      levels: [
        { id: "mobile-near", maximumDistance: 2600, featureIds: simplifiedFeatureIds, triangleBudget: 520 },
        { id: "mobile-silhouette", maximumDistance: 8000, featureIds: silhouetteFeatureIds, triangleBudget: 160 },
      ],
    },
  ],
  previews: [
    {
      device: "desktop",
      cameraPosition: [980, 720, 1180],
      cameraTarget: [0, 260, 40],
      background: "dark",
    },
    {
      device: "mobile",
      cameraPosition: [1200, 760, 1650],
      cameraTarget: [0, 250, 40],
      background: "dark",
    },
  ],
  tags: ["cyber-factory", "break-room", "beverage", "menu", "planned"],
};

export const coffeeMachineDefinition: ModelAssetDefinition = {
  manifest: coffeeMachineManifest,
  createModel: () => createCoffeeMachine(),
};
