export {
  blockAvatarFeatureIds,
  blockAvatarGroupIds,
  blockAvatarJointIds,
  blockAvatarParameterLimits,
  createBlockAvatar,
  createChair,
  createDesk,
  createLaptop,
  createMonitor,
  createTower,
  defaultBlockAvatarParameters,
  defaultOfficeChairParameters,
  defaultOfficeDeskParameters,
  defaultOfficeLaptopParameters,
  defaultOfficeMonitorParameters,
  defaultOfficeTowerParameters,
  normalizeBlockAvatarParameters,
  normalizeOfficeChairParameters,
  normalizeOfficeDeskParameters,
  normalizeOfficeLaptopParameters,
  normalizeOfficeMonitorParameters,
  normalizeOfficeTowerParameters,
  officeChairFeatureIds,
  officeChairGroupIds,
  officeChairLegFeatureId,
  officeChairParameterLimits,
  officeChairWheelFeatureId,
  officeDeskFeatureIds,
  officeDeskGroupIds,
  officeDeskParameterLimits,
  officeLaptopFeatureIds,
  officeLaptopGroupIds,
  officeLaptopJointIds,
  officeLaptopParameterLimits,
  officeMonitorFeatureIds,
  officeMonitorGroupIds,
  officeMonitorParameterLimits,
  officeTowerFanFeatureId,
  officeTowerFeatureIds,
  officeTowerGroupIds,
  officeTowerParameterLimits,
  type BlockAvatarParameters,
  type OfficeChairParameters,
  type OfficeDeskParameters,
  type OfficeLaptopParameters,
  type OfficeMonitorParameters,
  type OfficeTowerParameters,
} from "@solidloom/shared";
