import type { ModelAssetDefinition, ModelAssetManifest } from "@solidloom/shared";
import {
  createSnackCabinet,
  defaultSnackCabinetParameters,
  snackCabinetFeatureIds,
  snackCabinetGroupIds,
  snackCabinetJointIds,
} from "./model.js";

const allFeatureIds = Object.values(snackCabinetFeatureIds);
const silhouetteFeatureIds = [
  snackCabinetFeatureIds.base,
  snackCabinetFeatureIds.back,
  snackCabinetFeatureIds.leftColumn,
  snackCabinetFeatureIds.rightColumn,
  snackCabinetFeatureIds.top,
  snackCabinetFeatureIds.glassDoor,
  snackCabinetFeatureIds.pickupRecess,
];
const simplifiedFeatureIds = [
  ...silhouetteFeatureIds,
  snackCabinetFeatureIds.shelfOne,
  snackCabinetFeatureIds.shelfTwo,
  snackCabinetFeatureIds.shelfThree,
  snackCabinetFeatureIds.shelfFour,
  snackCabinetFeatureIds.productRowOne,
  snackCabinetFeatureIds.productRowTwo,
  snackCabinetFeatureIds.productRowThree,
  snackCabinetFeatureIds.pickupFlap,
  snackCabinetFeatureIds.paymentDisplay,
  snackCabinetFeatureIds.statusLight,
];

export const snackCabinetManifest: ModelAssetManifest = {
  schemaVersion: 1,
  id: "cyber-factory-snack-cabinet",
  displayName: "参数化零食售货机",
  description: "适用于办公室补给区的自动售货机，包含支付选择、出货取物、补货和库存挂接语义。",
  version: "1.0.0",
  kind: "asset",
  modelUnit: "mm",
  parameters: [
    {
      id: "width",
      label: "柜体宽度",
      type: "number",
      defaultValue: defaultSnackCabinetParameters.width,
      unit: "mm",
      minimum: 720,
      maximum: 1200,
      step: 20,
    },
    {
      id: "height",
      label: "柜体高度",
      type: "number",
      defaultValue: defaultSnackCabinetParameters.height,
      unit: "mm",
      minimum: 1600,
      maximum: 2300,
      step: 20,
    },
    {
      id: "depth",
      label: "柜体深度",
      type: "number",
      defaultValue: defaultSnackCabinetParameters.depth,
      unit: "mm",
      minimum: 440,
      maximum: 720,
      step: 20,
    },
    {
      id: "finish",
      label: "柜体配色",
      type: "select",
      defaultValue: defaultSnackCabinetParameters.finish,
      options: ["graphite", "porcelain", "sage"],
    },
  ],
  materials: [
    {
      id: "cabinet-metal",
      label: "金属柜体",
      material: "metal",
      color: "#202B31",
      featureIds: [
        snackCabinetFeatureIds.base,
        snackCabinetFeatureIds.back,
        snackCabinetFeatureIds.leftColumn,
        snackCabinetFeatureIds.rightColumn,
        snackCabinetFeatureIds.top,
      ],
    },
    {
      id: "shelf-metal",
      label: "金属层架",
      material: "metal",
      color: "#A8B6B8",
      featureIds: [
        snackCabinetFeatureIds.shelfOne,
        snackCabinetFeatureIds.shelfTwo,
        snackCabinetFeatureIds.shelfThree,
        snackCabinetFeatureIds.shelfFour,
      ],
    },
    {
      id: "display-glass",
      label: "透明柜门与屏幕",
      material: "glass",
      color: "#92D5DE",
      featureIds: [
        snackCabinetFeatureIds.glassDoor,
        snackCabinetFeatureIds.pickupFlap,
        snackCabinetFeatureIds.paymentDisplay,
      ],
    },
    {
      id: "service-plastic",
      label: "服务面板",
      material: "plastic",
      color: "#10181C",
      featureIds: [
        snackCabinetFeatureIds.pickupRecess,
        snackCabinetFeatureIds.refillPanel,
      ],
    },
    {
      id: "stock-packaging",
      label: "零食包装",
      material: "plastic",
      color: "#E88D4D",
      featureIds: [
        snackCabinetFeatureIds.productRowOne,
        snackCabinetFeatureIds.productRowTwo,
        snackCabinetFeatureIds.productRowThree,
        snackCabinetFeatureIds.statusLight,
      ],
    },
  ],
  placement: {
    upAxis: "y",
    groundY: 0,
    origin: [0, 0, 0],
    defaultScale: [1, 1, 1],
  },
  colliders: [
    {
      id: "snack-cabinet-body-collider",
      label: "柜体碰撞体",
      shape: "box",
      position: [0, defaultSnackCabinetParameters.height / 2, 0],
      rotation: [0, 0, 0],
      size: [
        defaultSnackCabinetParameters.width,
        defaultSnackCabinetParameters.height,
        defaultSnackCabinetParameters.depth,
      ],
      groupId: snackCabinetGroupIds.structure,
    },
    {
      id: "snack-cabinet-door-collider",
      label: "透明柜门碰撞体",
      shape: "box",
      position: [0, defaultSnackCabinetParameters.height * 0.61, defaultSnackCabinetParameters.depth / 2 + 12],
      rotation: [0, 0, 0],
      size: [
        defaultSnackCabinetParameters.width * 0.89,
        defaultSnackCabinetParameters.height * 0.68,
        18,
      ],
      groupId: snackCabinetGroupIds.glassDoor,
    },
  ],
  anchors: [
    {
      id: "snack-cabinet-front-approach",
      label: "正面接近位",
      kind: "approach",
      position: [0, 0, defaultSnackCabinetParameters.depth / 2 + 760],
      rotation: [0, 180, 0],
      range: 980,
      groupId: snackCabinetGroupIds.structure,
      tags: ["navigation", "front"],
    },
    {
      id: "snack-cabinet-select-item",
      label: "选择零食",
      kind: "interaction",
      position: [0, defaultSnackCabinetParameters.height * 0.53, defaultSnackCabinetParameters.depth / 2 + 260],
      rotation: [0, 180, 0],
      range: 760,
      groupId: snackCabinetGroupIds.service,
      tags: ["inventory", "select"],
    },
    {
      id: "snack-cabinet-pickup-item",
      label: "取走零食",
      kind: "interaction",
      position: [0, defaultSnackCabinetParameters.height * 0.16, defaultSnackCabinetParameters.depth / 2 + 240],
      rotation: [0, 180, 0],
      range: 680,
      groupId: snackCabinetGroupIds.pickup,
      tags: ["inventory", "pickup"],
    },
    {
      id: "snack-cabinet-stock-socket",
      label: "库存挂接点",
      kind: "socket",
      position: [0, defaultSnackCabinetParameters.height * 0.56, 0],
      rotation: [0, 0, 0],
      range: 360,
      groupId: snackCabinetGroupIds.products,
      tags: ["inventory", "stock"],
    },
    {
      id: "snack-cabinet-refill-stock",
      label: "后侧补货",
      kind: "interaction",
      position: [0, defaultSnackCabinetParameters.height * 0.56, -defaultSnackCabinetParameters.depth / 2 - 460],
      rotation: [0, 0, 0],
      range: 820,
      tags: ["inventory", "refill", "maintenance"],
    },
  ],
  joints: [{
    id: "snack-cabinet-pickup-flap",
    label: "取物挡板",
    jointId: snackCabinetJointIds.pickupFlap,
    semantic: "pickup-access",
  }],
  lod: [
    {
      device: "desktop",
      levels: [
        { id: "snack-cabinet-desktop-full", maximumDistance: 5000, featureIds: allFeatureIds, triangleBudget: 760 },
        { id: "snack-cabinet-desktop-medium", maximumDistance: 10000, featureIds: simplifiedFeatureIds, triangleBudget: 420 },
        { id: "snack-cabinet-desktop-silhouette", maximumDistance: 20000, featureIds: silhouetteFeatureIds, triangleBudget: 180 },
      ],
    },
    {
      device: "mobile",
      levels: [
        { id: "snack-cabinet-mobile-near", maximumDistance: 4200, featureIds: simplifiedFeatureIds, triangleBudget: 380 },
        { id: "snack-cabinet-mobile-silhouette", maximumDistance: 12000, featureIds: silhouetteFeatureIds, triangleBudget: 160 },
      ],
    },
  ],
  previews: [
    {
      device: "desktop",
      cameraPosition: [2100, 1550, 2500],
      cameraTarget: [0, 900, 0],
      background: "dark",
    },
    {
      device: "mobile",
      cameraPosition: [2800, 1700, 3350],
      cameraTarget: [0, 880, 0],
      background: "dark",
    },
  ],
  tags: ["cyber-factory", "office", "inventory", "snack", "planned"],
};

export const snackCabinetDefinition: ModelAssetDefinition = {
  manifest: snackCabinetManifest,
  createModel: () => createSnackCabinet(),
};
