export {
  createSnackCabinet,
  defaultSnackCabinetInventory,
  defaultSnackCabinetParameters,
  normalizeSnackCabinetParameters,
  snackCabinetFeatureIds,
  snackCabinetGroupIds,
  snackCabinetJointIds,
  snackCabinetProductFeaturePrefix,
  type SnackCabinetCreateInput,
  type SnackCabinetFinish,
  type SnackCabinetParameters,
  type SnackCabinetProductDefinition,
  type SnackCabinetShelfInventory,
} from "@solidloom/shared";
